#!/bin/bash
mvn install:install-file -Dfile=ojdbc14.jar -DgroupId=com.oracle  -DartifactId=ojdbc14 -Dversion=10 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=ojdbc6.jar -DgroupId=com.oracle  -DartifactId=ojdbc6 -Dversion=11.2.0.4 -Dpackaging=jar -DgeneratePom=true
